import { FireIcon } from "@heroicons/react/24/outline"

export const tours = [
  {
    title: "Nacho Average Taco Tour",
    desc: "Authentic Mexican hidden gems with generous portions and delicious drinks",
    type: "Mexican",
    icon: FireIcon,
    price: "$149",
    duration: "4hrs",
    status: "active",
    link: "/tours/naples-taco-tour",
    location: "Naples",
  },
  {
    title: "Naples Pizza Wars Tour",
    desc: "You be the judge of the four most popular pizzas in Naples. It's a fight to the end!",
    type: "Pizza",
    icon: FireIcon,
    price: "$149",
    duration: "4hrs",
    status: "active",
    link: "/tours/naples-pizza-wars",
    location: "Naples",
  },
  {
    title: "Naples Italian Tour",
    desc: "Enjoy wine, a full meal plus dessert at 3 family-owned authentic trattorias",
    type: "Italian",
    icon: FireIcon,
    price: "$175",
    duration: "4hrs",
    status: "active",
    link: "/tours/naples-italian-tour",
    location: "Naples",
  },

  // {
  //   title: "N Naples/Bonita Brewery Tour",
  //   desc: "Visit 3 breweries and grab tasty snacks at the food trucks or on-site kitchens",
  //   type: "Beer",
  //   icon: FireIcon,
  //   price: "$149",
  //   duration: "4hrs",
  //   status: "active",
  //   link: "/tours/brewery",
  //   location: "Naples / Bonita",
  // },
  // {
  //   title: "Taste of Bonita Tour",
  //   desc: "Experience the delights of downtown Bonita and explore historic Old 41",
  //   type: "Artisanal",
  //   icon: FireIcon,
  //   price: "$149",
  //   duration: "4hrs",
  //   status: "active",
  //   link: "/tours/bonita",
  //   location: "Bonita",
  // },
  // {
  //   title: "Naples Dessert Tour",
  //   desc: "A sweet escape — explore Naples' best gelato, pastries, and more in one sugar-filled afternoon",
  //   type: "Dessert",
  //   icon: FireIcon,
  //   price: "$149",
  //   duration: "4hrs",
  //   status: "active",
  //   link: "/tours/dessert-naples",
  //   location: "Naples",
  // },
  // {
  //   title: "Marco Island Seafood Tour",
  //   desc: "Savor fresh catches and waterfront views on Marco’s best seafood stops",
  //   type: "Seafood",
  //   icon: FireIcon,
  //   price: "$165",
  //   duration: "4hrs",
  //   status: "active",
  //   link: "/tours/seafood-marco",
  //   location: "Marco Island",
  // },
  // {
  //   title: "Fort Myers Brewery Tour",
  //   desc: "Discover the best breweries across Fort Myers & Cape Coral with chilled pours and fun vibes",
  //   type: "Beer",
  //   icon: FireIcon,
  //   price: "$149",
  //   duration: "4hrs",
  //   status: "active",
  //   link: "/tours/brewery-fortmyers",
  //   location: "Fort Myers / Cape Coral",
  // },
  // {
  //   title: "Fort Myers Distillery & Tasting Tour",
  //   desc: "Sample small-batch spirits, cocktails, and curated bites across local distilleries",
  //   type: "Spirits",
  //   icon: FireIcon,
  //   price: "$149",
  //   duration: "4hrs",
  //   status: "active",
  //   link: "/tours/distillery-fortmyers",
  //   location: "Fort Myers / Cape Coral",
  // },
  // {
  //   title: "Fort Myers Seafood Tour",
  //   desc: "From crab cakes to ceviche — dive into the Gulf's finest flavors with this Fort Myers tour",
  //   type: "Seafood",
  //   icon: FireIcon,
  //   price: "$149",
  //   duration: "4hrs",
  //   status: "active",
  //   link: "/tours/seafood-fortmyers",
  //   location: "Fort Myers / Cape Coral",
  // },
  // {
  //   title: "Naples Brunch Tour (Coming Soon)",
  //   desc: "The only thing better than having brunch is having 3!",
  //   type: "Brunch",
  //   icon: FireIcon,
  //   price: "",
  //   duration: "4hrs",
  //   status: "coming",
  //   link: "",
  //   location: "Naples",
  // },
]
